version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - lamp-net

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    networks:
      - lamp-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  lamp-net:

volumes:
  mysql-data:
