apiVersion: v1
kind: Service
metadata:
  name: lamp-frontend
spec:
  type: NodePort
  selector:
    app: lamp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
