apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lamp-frontend
  template:
    metadata:
      labels:
        app: lamp-frontend
    spec:
      containers:
      - name: nginx-php
        image: my-nginx-php:latest
        ports:
        - containerPort: 80
